version: 3.7

services:
  node:
    build:
      context: .
      args:
        - NODE_ENV=development
      environment:
        - NODE_ENV=development
      ports:
        - "80:3000"   # application port
        - "9229:9229" # default node --inspect port
      volumes:
        - ".:/home/node/app:delegated"
        - "hide_host_modules:/home/node/app/node_modules"
      # nodemon should be in your devDependencies
      command: ../node_modules/.bin/nodemon --inspect=0.0.0.0:9229 ./bin/www

volumes:
  hide_host_modules:
